board/urls.py
from django.urls import path

from .views import base_views, comment_views, post_views, user_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('', 
        base_views.index, name='index'),
    path('post/<int:post_id>/', 
        base_views.detail, name='detail'),
    path('<str:category_url>/',
        base_views.category, name='category'),
    # When use generic
    #path('<int:pk>/', views.DetailView.as_view()),


    # user_views.py
    path('user/<int:user_id>/profile/',
        user_views.user_profile, name='user_profile'),
    path('user/<int:user_id>/notification/',
        user_views.user_notification, name='user_notification'),

    # comment_views.py
    path('comment/create/<int:post_id>/', 
        comment_views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', 
        comment_views.comment_delete, name='comment_delete'),

    # post_views.py
    path('<str:category_url>/post/create/',
        post_views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', 
        post_views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', 
        post_views.post_delete, name='post_delete'),
    path('post/like/<int:post_id>/',
        post_views.post_like, name='post_like'),
    path('post/dislike/<int:post_id>/',
        post_views.post_dislike, name='post_dislike'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='Email')

    class Meta:
        model = User
        fields = {'username', 'email', 'password1', 'password2'}

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render

from common.forms import UserForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends "base.html" %}
{% block content %}

<section>
  <form method="post" class="post-form" action="{% url 'common:login' %}">
    {% csrf_token %}
    <!-- After Login url -->
    <input type="hidden" name="next" value="{{ next }}">
    {% include "form_errors.html" %}
    <div class="container py-5 h-100">
      <div class="row d-flex h-100 justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">

          <div class="card bg-secondary text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
                <div class="mb-md-5 mt-md-4 pb-5">
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>
                  <!-- name -->
                  <div class="form-outline form-white mb-4">
                    <input type="text" id="username" class="form-control form-control-lg" name="username"
                      value="{{ form.username.value|default_if_none:'' }}" placeholder="ID"/>
                  </div>
                  <!-- password -->
                  <div class="form-outline form-white mb-4">
                    <input type="password" id="password" class="form-control form-control-lg" name="password"
                      value="{{ form.password.value|default_if_none:'' }}" placeholder="Password" />
                  </div>
                  
                  <!-- Forgot Password -->
                  <p class="small mb-5 pb-lg-2">
                    <a class="text-white-50" href="#!">
                      Forgot password?
                    </a>
                  </p>
                  
                  <!-- submit button -->
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                  
                  <!-- OAUTH icons -->
		  <!--
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                  </div>
		  -->  
                </div>
                <!-- Sign up -->
                <div>
                  <p class="mb-0">Don't have an account? <a href="{% url 'common:signup' %}" class="text-white-50 fw-bold">Sign Up</a></p>
                </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock %}

templates/common/login_form.html
{% extends "base.html" %}
{% block content %}

<section class="vh-100 gradient-custom">
  <form method="post" class="post-form" action="{% url 'common:login' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
                <div class="mb-md-5 mt-md-4 pb-5">
  
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>

                  <div class="form-outline form-white mb-4">
                    <input type="text" id="username" class="form-control form-control-lg" name="username"
                      value="{{ form.username.value|default_if_none:'' }}" placeholder="ID"/>
                  </div>
  
                  <div class="form-outline form-white mb-4">
                    <input type="password" id="password" class="form-control form-control-lg" name="password"
                      value="{{ form.password.value|default_if_none:'' }}" placeholder="Password" />
                  </div>
    
                  <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
    
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                  </div>
  
                </div>
  
                <div>
                  <p class="mb-0">Don't have an account? <a href="#!" class="text-white-50 fw-bold">Sign Up</a></p>
                </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}

<section>
  <form method="post" class="post-form" action="{% url 'common:signup' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          
          <div class="card bg-secondary text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
                <div class="mb-md-5 mt-md-4 pb-5">
  
                  <h2 class="fw-bold mb-2 text-uppercase">Sign up</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>

                  <div class="form-outline form-white mb-4">
                    <input type="text" id="username" class="form-control form-control-lg" name="username"
                      value="{{ form.username.value|default_if_none:'' }}" placeholder="ID"/>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="email" id="email" class="form-control form-control-lg" name="email"
                      value="{{ form.email.value|default_if_none:'' }}" placeholder="Email" />
                  </div>
  
                  <div class="form-outline form-white mb-4">
                    <input type="password" id="password1" class="form-control form-control-lg" name="password1"
                      value="{{ form.password1.value|default_if_none:'' }}" placeholder="Password" />
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" id="password2" class="form-control form-control-lg" name="password2"
                      value="{{ form.password2.value|default_if_none:'' }}" placeholder="Password confirm" />
                  </div>

    
                  <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="{% url 'common:login' %}">Already a member?</a></p>
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Sign up</button>
                  <!--
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                  </div>
  		  -->
                </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</section>
{% endblock %}