board/urls.py
from django.urls import path

from .views import base_views, comment_views, post_views, user_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('', 
        base_views.index, name='index'),
    path('post/<int:post_id>/', 
        base_views.detail, name='detail'),
    path('<str:category_url>/',
        base_views.category, name='category'),
    # When use generic
    #path('<int:pk>/', views.DetailView.as_view()),


    # user_views.py
    path('user/<int:user_id>/profile/',
        user_views.user_profile, name='user_profile'),
    path('user/<int:user_id>/notification/',
        user_views.user_notification, name='user_notification'),

    # comment_views.py
    path('comment/create/<int:post_id>/', 
        comment_views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', 
        comment_views.comment_delete, name='comment_delete'),

    # post_views.py
    path('<str:category_url>/post/create/',
        post_views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', 
        post_views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', 
        post_views.post_delete, name='post_delete'),
    path('post/like/<int:post_id>/',
        post_views.post_like, name='post_like'),
    path('post/dislike/<int:post_id>/',
        post_views.post_dislike, name='post_dislike'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/views/base_views.py
from django.core.checks import messages
from django.utils import timezone
from board.models import Post, Category, Comment
from django.db.models import Q, Count
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required


def index(request):
    category_list = Category.objects.all()
    post_list = []
    for category in category_list:
        posts = Post.objects.filter(category=category).order_by('-create_date')[:5]
        post_list.append(posts)

    context = {'context': zip(category_list, post_list)}
    return render(request, 'board/index.html', context)


def category(request, category_url):
    category = Category.objects.get(url=category_url)
    post_list = Post.objects.filter(category=category)
    
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'like':
        post_list = post_list.annotate(num_liked=Count('liked')).order_by('-num_liked', '-create_date')
    elif so == 'comment':
        post_list = post_list.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    elif so == 'hit':
        post_list = post_list.order_by('-hits', '-create_date')
    else:  # recent
        post_list = post_list.order_by('-create_date')

    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)|
            Q(comment__author__username__icontains=kw)
        ).distinct()

    paginator = Paginator(post_list, 10)
    page_obj = paginator.get_page(page)

    context = {'posts': page_obj, 'page': page, 'kw': kw, 'so': so, 'category': category}
    return render(request, 'board/post_list.html', context)

    
@login_required(login_url='common:login')
def detail(request, post_id):
    try:
        now = timezone.now()
        # 수정
        post = Post.objects.prefetch_related('comment_set').get(pk=post_id)
        comments = Comment.objects.filter(post=post).select_related('author')

        notifications = request.user.notification.filter(read_date__isnull=True).filter(post=post)

        for notification in notifications:
            notification.read_date = now
            notification.save()
            
    except Exception as e:
        print(e)
        return redirect('board:index')

    context = {'post': post, 'comments': comments}
    return render(request, 'board/post_detail.html', context)

templates/base.html
{%load static%}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <!-- Icon -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
        <title>...'몰?루'가 뭐지?</title>
    </head>
    <body class="bg-dark">
        {% include "navbar.html"%}
        {% block content %}
        {% endblock %}
        
        <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'bootstrap.min.js' %}"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

templates/form_errors.html
{% if form.errors %}
            <div class="alert alert-fixed rounded alert-secondary alert-dismissible fade show" role="alert">
                <strong>
                    {{ form.errors }}
                </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
{% endif %}

templates/navbar.html
<nav class="navbar bg-dark pos-f-t navbar-exapnd-lg navbar-dark border-bottom">
    <div class="container-fluid">
        <!-- 배너 -->
        <a class="navbar-brand" href="{% url 'board:index' %}" tabindex="-1">홈</a>

        {% if 'free' in request.path or 'free' == post.category.url %}
            <a class="navbar-brand" href="{% url 'board:category' 'free'%}" tabindex="-1">자유 게시판</a>
        {% elif 'stock' in request.path or 'stock' == post.category.url %}
            <a class="navbar-brand" href="{% url 'board:category' 'stock'%}" tabindex="-1">주식 게시판</a>
        {% endif %}
        
        <!-- notification -->
        <ul class="navbar-nav">
            <li class="navitem">
                {% if user.is_authenticated %}
                    <a class="navbar-text ms-auto pe-3" tabindex="-1">
                        {% if user.profile.unread_notification > 0 %}
                            <a class="text-white text-decoration-none pe-3" href="{% url 'board:user_notification' user.id %}" tabindex="-1">
                                <i class="far fa-bell fa-lg"></i>
                                <span class="badge bg-primary rounded">{{ user.profile.unread_notification }}</span>
                            </a>
                        {% else %}
                            <a class="text-secondary text-decoration-none pe-3" href="{% url 'board:user_notification' user.id %}" tabindex="-1">
                                <i class="far fa-bell fa-lg"></i>
                                <span class="badge bg-secondary rounded">{{ user.profile.unread_notification }}</span>
                            </a>
                        {% endif %}
                    </a>
                {% endif %}
                <!-- Toggle Button -->
                <button class="navbar-toggler" tabindex="-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#navigationBar" aria-expanded="false" aria-controls="navigationBar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </li>
        </ul>
        <div class="offcanvas bg-dark offcanvas-end" data-bs-scroll="true" tabindex="-1" id="navigationBar" aria-labelledby="navigationBarLabel"
            style="width:250px;">
            
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" style="color:seashell">메뉴</h5>
                <button class="btn-close text-reset" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <hr>
            <!-- Menu -->
            <div class="offcanvas-body">
                {% include "navmenu.html" %}
            </div>
        </div>
    </div>
</nav>

templates/navmenu.html
<ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
    <li>
        {% if user.is_authenticated %}
            <a class="navbar-text text-decoration-none me-auto" href="{% url 'common:logout' %}" tabindex="-1">Logout</a>
        {% else %}
            <a class="navbar-text text-decoration-none me-auto" href="{% url 'common:login' %}" tabindex="-1">Login</a>
        {% endif %}
    </li>
    <hr>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">
            홈
        </a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'board:user_profile' user.id %}">
            프로필
        </a>
    </li>
    {% endif %}
    <hr>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'board:category' 'free' %}">
            - 자유 게시판
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'board:category' 'stock' %}">
            - 주식 게시판
        </a>
    </li>
    <!--
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navigationBarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navigationBarDropdown">
            <li><a class="dropdown-item" href="#">dropdown-item1</a></li>
            <li><a class="dropdown-item" href="#">dropdown-item2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">dropdown-item3</a></li>
        </ul>
    </li>
    -->
</ul>