board/urls.py
from django.urls import path

from .views import base_views, comment_views, post_views, user_views

app_name = 'board'

urlpatterns = [
    # base_views.py
    path('', 
        base_views.index, name='index'),
    path('post/<int:post_id>/', 
        base_views.detail, name='detail'),
    path('<str:category_url>/',
        base_views.category, name='category'),
    # When use generic
    #path('<int:pk>/', views.DetailView.as_view()),


    # user_views.py
    path('user/<int:user_id>/profile/',
        user_views.user_profile, name='user_profile'),
    path('user/<int:user_id>/notification/',
        user_views.user_notification, name='user_notification'),

    # comment_views.py
    path('comment/create/<int:post_id>/', 
        comment_views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', 
        comment_views.comment_delete, name='comment_delete'),

    # post_views.py
    path('<str:category_url>/post/create/',
        post_views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', 
        post_views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', 
        post_views.post_delete, name='post_delete'),
    path('post/like/<int:post_id>/',
        post_views.post_like, name='post_like'),
    path('post/dislike/<int:post_id>/',
        post_views.post_dislike, name='post_dislike'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index, name='index')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta, datetime, timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    @property
    def unread_notification(self):
        i = 0
        for notification in self.user.notification.all():
            if notification.read_date is None:
                i += 1
        return i

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Category(models.Model):
    title = models.CharField(max_length=20)
    url = models.CharField(max_length=10)
    class Meta:
            verbose_name_plural = "Categories"
    def __str__(self):
        return self.title

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET('Deleted:User'), related_name='author_post')
    subject = models.CharField(max_length=50)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    liked = models.ManyToManyField(User, related_name='liked_post')
    disliked = models.ManyToManyField(User, related_name='disliked_post')
    hits = models.PositiveIntegerField(default=0)

    @property
    def is_recent(self):
        return (datetime.now(timezone.utc) - self.create_date) < timedelta(days=1)

    def update_hits(self):
        self.hits += 1
        self.save()
        return ''
        
    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET("Deleted:User"), related_name='author_comment')
    content = models.TextField(max_length=200)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content


'''
Post <- 누군가 댓글을 달면 알림
Post 작성자 Post's Comment 작성자에게
'''
class Notification(models.Model):
    user = models.ForeignKey(User, related_name='notification', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    read_date = models.DateTimeField(null=True, blank=True)

    @property
    def invoked_user(self):
        return self.comment.author

board/forms.py
from django import forms
from django.forms import widgets
from board.models import Comment, Post, Notification
from django_summernote.widgets import SummernoteWidget

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']
        labels = {
            'subject': 'Subject',
            'content': 'Content',
        }
        widgets = {
            'content': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '500px'}}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels ={
            'content': 'Content',
        }

board/views/base_views.py
from django.core.checks import messages
from django.utils import timezone
from board.models import Post, Category, Comment
from django.db.models import Q, Count
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required


def index(request):
    category_list = Category.objects.all()
    post_list = []
    for category in category_list:
        posts = Post.objects.filter(category=category).order_by('-create_date')[:5]
        post_list.append(posts)

    context = {'context': zip(category_list, post_list)}
    return render(request, 'board/index.html', context)


def category(request, category_url):
    category = Category.objects.get(url=category_url)
    post_list = Post.objects.filter(category=category)
    
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'like':
        post_list = post_list.annotate(num_liked=Count('liked')).order_by('-num_liked', '-create_date')
    elif so == 'comment':
        post_list = post_list.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    elif so == 'hit':
        post_list = post_list.order_by('-hits', '-create_date')
    else:  # recent
        post_list = post_list.order_by('-create_date')

    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)|
            Q(comment__author__username__icontains=kw)
        ).distinct()

    paginator = Paginator(post_list, 10)
    page_obj = paginator.get_page(page)

    context = {'posts': page_obj, 'page': page, 'kw': kw, 'so': so, 'category': category}
    return render(request, 'board/post_list.html', context)

    
@login_required(login_url='common:login')
def detail(request, post_id):
    try:
        now = timezone.now()
        # 수정
        post = Post.objects.prefetch_related('comment_set').get(pk=post_id)
        comments = Comment.objects.filter(post=post).select_related('author')

        notifications = request.user.notification.filter(read_date__isnull=True).filter(post=post)

        for notification in notifications:
            notification.read_date = now
            notification.save()
            
    except Exception as e:
        print(e)
        return redirect('board:index')

    context = {'post': post, 'comments': comments}
    return render(request, 'board/post_detail.html', context)

board/views/comment_views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.checks import messages
from board.models import Post, Comment, Notification, User
from board.forms import CommentForm

@login_required(login_url='common:login')
def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            now = timezone.now()

            comment = Comment(post=post, author=request.user, content=request.POST.get('content'), create_date=now)
            comment.save()
            
            Notification(user=post.author, post=post, comment=comment, create_date=now).save()
            # 수정 postgresql migrate -> distinct on 가능
            activities = Comment.objects.filter(post=post)\
                .exclude(author__in=[request.user,post.author])\
                    .distinct('author')\
                        .select_related('author')

            for activity in activities:
                Notification(user=activity.author, post=post, comment=comment, create_date=now).save()

            return redirect('board:detail', post_id=post_id)

    else:
        form = CommentForm()

    context = {'post': post, 'form':form}
    return render(request, 'board/post_detail.html', context)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, 'Permission error.')
        return redirect('board:detail', post_id=comment.post.id)

    comment.delete()
    return redirect('board:detail', post_id=comment.post.id)

board/views/post_views.py
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages

from board.models import Category, Post
from board.forms import PostForm



@login_required(login_url='common:login')
def post_create(request, category_url):
    if request.method == 'POST':
        form = PostForm(request.POST)
        category = Category.objects.get(url=category_url)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.category = category
            post.create_date = timezone.now()
            post.save()
            return redirect('board:category', category.url)
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'board/post_create_form.html', context)

@login_required(login_url='common:login')
def post_modify(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'Permission error.')
        return redirect('board:detail', post_id=post_id)
        
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.modify_date = timezone.now()
            post.save()
            return redirect('board:detail', post_id=post_id)
    else:
        form = PostForm(instance=post)
    context = {'form':form}
    return render(request, 'board/post_create_form.html', context)

@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, 'Permission error.')
        return redirect('board:detail', post_id=post_id)
    post.delete()
    return redirect('board:index')

@login_required(login_url='common:login')
def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user in post.disliked.all():
        messages.error(request, "이미 비추천에 투표하였습니다.")
    else:
        if request.user in post.liked.all():
            post.liked.remove(request.user)
        else:
            post.liked.add(request.user)
    return redirect('board:detail', post_id=post_id)

@login_required(login_url='common:login')
def post_dislike(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user in post.liked.all():
        messages.error(request, "이미 추천에 투표하였습니다.")
    else:
        if request.user in post.disliked.all():
            post.disliked.remove(request.user)
        else:
            post.disliked.add(request.user)
    return redirect('board:detail', post_id=post_id)

board/views/user_views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from board.models import Post, Comment, Notification

@login_required(login_url='common:login')
def user_profile(request, user_id):
    user = User.objects.get(pk=user_id)
    posts = Post.objects.filter(author=user).order_by('-create_date')
    comments = Comment.objects.filter(author=user).order_by('-create_date')
    agg = {'liked_sum': posts.aggregate(Sum('liked'))['liked__sum'],
            'disliked_sum': posts.aggregate(Sum('disliked'))['disliked__sum']}

    posts = Paginator(posts, 10).get_page(1)
    comments = Paginator(comments, 10).get_page(1)

    context = {'user':user, 'posts':posts, 'comments':comments, 'agg':agg}
    return render(request, 'board/user_profile.html', context)

def user_notification(request, user_id):
    user = User.objects.get(pk=user_id)
    notifications = Notification.objects.filter(user=user).order_by('read_date','-create_date')
    #notifications = Notification.objects.filter(user=user).filter(read_date__isnull=True).order_by('-read_date','-create_date')
    context = {'user': user, 'notifications': notifications}
    return render(request, 'board/user_notification.html', context)

templates/board/comment_create_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">Comment Registeration</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">Content</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/board/comment_form.html
<!-- Comment List -->
<div class="container container-fluid pt-3 px-4">
    <!-- Header -->
    <h5 class="text pb-3">
        <strong>Comments</strong>
    </h5>

    <!-- Comment Items -->
    {% if post.comment_set.count %}
        {%for comment in comments %}
        <dl class="row rounded-3 border-bottom py-3" style="background: #333333;">
            <!-- if click Comment, Reply -->
            <div class="col row position-relative">
                <!-- Logic when Clicked -->
                <dt class="ms-1">
                    <a href="#" class="stretched-link"></a>
                    {{ comment.author }}
                </dt>
                
                <!-- Content -->
                <dd class="col-sm text-wrap text-break">
                    {{ comment.content|safe }}
                </dd>
                <!-- Create Date-->
                <dd class="small col-sm-3">
                    {{ comment.create_date }}    
                </dd>
            </div>
            <!-- Delete Icon -->
            <div class="col-1 text-end me-3">
                {% if comment.author == request.user %}
                    <a type="button" class="btn text-white" data-bs-toggle="modal"
                        data-bs-target="#deleteComment">
                        <i class="far fa-trash-alt"></i>
                    </a>
                    <!-- Modal popup-->
                    <div class="modal fade" id="deleteComment" tabindex="-1" aria-labelledby="modifyModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-dark" id="modifyModalLabel">정말 삭제 하시겠습니까?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                                    <a class="btn btn-primary"
                                        href="{% url 'board:comment_delete' comment.id  %}">네</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </dl>
    {%endfor%}
    {% else %}
        <div class="container-flud text-center pb-3">
            No Comment.
        </div>
    {% endif %}
</div>

templates/board/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container container-fluid">
    {% for category, posts in context %}
    <br>
        <div class="container-sm container-fluid border rounded-3">
            <div class="h5 pt-3">
                {{ category.title }}
            </div>
            <div>
            <table class="table table-dark align-middle">
                <thead>
                    <tr class="text-center">
                        <th class="col-6 text-truncate">제목</th>
                        <th class="col-2 text-truncate">글쓴이</th>
                        <th class="col-2">작성일</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% if category.post_set.count > 0%}
                    {% for post in posts %}
                        <tr>
                            <td class="ps-3 text-truncate" style="max-width: 150px">
                                {% if post.is_recent %}
                                    <i class="fas fa-exclamation fa-xsm" style="color:orange"></i>
                                {% endif %}
                                <a href="{% url 'board:detail' post.id %}" class="text-decoration-none text-white">
                                    {{ post.subject }}
                                    {% if post.comment_set.count > 0 %}
                                        <span class="text-danger small ml-2">
                                            [{{ post.comment_set.count }}]
                                        </span>
                                    {% endif %}
                                </a>
                            </td>
                            <td class="text-center">{{ post.author }}</td>
                            <td class="text-center">{{ post.create_date|timesince }}</td>
                        </tr>
                    {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">No data.</td>
                        </tr>
                    {% endif %}
                </tbody>
                <tfoot>
                    <tr class="text-end">
                        <td colspan="3">
                            <a href="{% url 'board:category' category.url %}" class="text-decoration-none text-white">더 보기</a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/board/main_page.html
{% extends 'base.html' %}
{% include 'board/post_list.html' %}


{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.page-link').on('click', function(){
            $('#page').val($(this).data('page'));
            $('#searchForm').submit();
        });

        $('#btn_search').on('click', function(){
            $('#kw').val($('.kw').val());
            $('#page').val(1);
            $('#searchForm').submit();
        });

        $(".so").on('change', function() {
            $("#so").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
    });
</script>
{% endblock %}

templates/board/post_create_form.html
{%extends 'base.html'%}
{%block content%}
<!--
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{form.as_p}}
    </table> 
    <input type="submit" value="제출">
</form>
-->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post", class="post-form my-3">
        {%csrf_token%}
        {%if form.errors%}
        <div class="alert alert-danger" role="alert">
            {%for field in form%}
                {%if field.errors%}
                <strong>{{field.label}}</strong>
                {{field.errors}}
                {%endif%}
            {%endfor%}
        </div>
        {%endif%}
        <div class="form-group">
            <label for="subject" class="my-2">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="content" class="my-2">Content</label>
                {{ form.content }}
            <!--
            <textarea contentEditable="true" class="form-control" name="content" id="content" rows="15" style="resize: none;">
                {{form.content|default_if_none:''}}
            </textarea>
            -->
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/board/post_form.html
<!-- Post Header -->
<div class="row">
    <!-- Subject -->
    <div class="col">
        <h1 class="h2">{{post.subject}}</h1>
    </div>
    <!-- Create date -->
    <div class="col text-muted text-end">
        <small>{{post.create_date}}</small>
    </div>
</div>

    <!-- Chcek valid route -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
    {% endif %}
<!-- Author, Modify/Delete -->
<span class="small text">
    <span class="text-muted">글쓴이:</span> 
    {{ post.author }} 

    {% if post.author == request.user %}    
    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal"
        data-bs-target="#postModify">
        수정
    </button>
    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
        data-bs-target="#postDelete">
        삭제
    </button>
    <!-- Modal popup-->
    <div class="modal fade" id="postModify" tabindex="-1" aria-labelledby="postModifyLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h5 class="modal-title text-dark" id="postModifyLabel">정말 수정 하시겠습니까?</h5>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
              <a class="btn btn-primary"
              href="{% url 'board:post_modify' post.id  %}">네</a>
            </div>
          </div>
        </div>
      </div>
    <div class="modal fade" id="postDelete" tabindex="-1" aria-labelledby="postDeleteLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <h5 class="text-dark" id="postDeleteLabel">정말 삭제 하시겠습니까?</h5>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
              <a class="btn btn-primary"
              href="{% url 'board:post_delete' post.id  %}">네<sp></a>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
</span>

<!-- Content -->
<div class="container border-bottom border-top container-fluid py-5 mt-3 mx-auto">
    {{ post.content|safe|linebreaksbr}}
</div>

<!-- Likes -->
<div class="col-12 text-center justify-content-center border-bottom border-secondary pb-3">
    <!-- 추천영역 -->
    <div class="card start-50 translate-middle text-black" style="width: 5rem; border-radius: 1rem;">
        <span>
            <span class="text-primary">{{post.liked.count}}</span> / <span class="text-danger">{{post.disliked.count}}</span>
        </span>
    </div>
    <span>
        <a href="#" data-uri="{% url 'board:post_like' post.id %}"
          class="like btn btn-sm btn-primary btn-block my-1">추천</a>
        <a href="#" data-uri="{% url 'board:post_dislike' post.id %}"
          class="dislike btn btn-sm btn-danger btn-block my-1">비추천</a>
    </span>
</div>

templates/board/post_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<div class="container position-relative py-5">
    <div class="row justify-content-between my-3">
        <div class="inline-block col-4 col-sm-2">
            <select class="form-control so" tabindex="-1">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>Recent</option>
                <option value="like" {% if so == 'like' %}selected{% endif %}>Like</option>
                <option value="hit" {% if so == 'hit' %}selected{% endif %}>Hit</option>
                <option value="comment" {% if so == 'comment' %}selected{% endif %}>Comment</option>
            </select>
        </div>
        <div class="col text-end pb-3">
            <a href="{% url 'board:post_create' category.url %}" class="btn btn-primary">글쓰기</a>
        </div>
    </div>
    <table class="table table-hover table-dark">
        <thead>
            <tr class="text-center">
                <th class="col-1">번호</th>
                <th class="col">제목</th>
                <th class="col-2">글쓴이</th>
                <th class="col-2">작성일</th>
                <th class="col-1">조회</th>
                <th class="col-1">추천</th>
            </tr>
        </thead>
        <tbody>
        <!-- Post List -->
        {%if posts %}
            {%for post in posts %}
            <tr class="align-middle">
                <!-- Post ID -->
                <td class="text-center">
                    {{ posts.paginator.count|sub:posts.start_index|sub:forloop.counter|add:1 }}
                </td>
                <!-- Subject -->
                <td>
                    <a href="{% url 'board:detail' post.id %}" class="text-light text-decoration-none">
                        {{ post.subject }}
                        {% if post.is_recent %}
                            <i class="fas fa-exclamation fa-xsm" style="color:orange"></i>
                        {% endif %}
                    </a>
                    <!-- Comment count -->
                    {% if post.comment_set.count > 0 %}
                        <span class="text-danger small ml-2">
                            [{{ post.comment_set.count }}]
                        </span>
                    {% endif %}
                </td>
                <!-- Author -->
                <td class="text small text-center">
                    <!-- 클릭 시 유저 정보 -->
                    <a href="{% url 'board:user_profile' post.author.id %}" class="text-light text-decoration-none">
                        {{ post.author }}
                    </a>
                </td>
                <!-- Create Date -->
                <td class="text-muted text-center small">
                    {{ post.create_date|date:'Y.m.d. a h:i' }}
                </td>
                <!-- hits -->
                <td class="text-center">
                    {{ post.hits }}
                </td>
                <!-- Likes -->
                <td class="text-center">
                    {{ post.liked.count}}
                </td>
            </tr>
            {%endfor%}
        {%else%}
            <tr>
                <td colspan="3">No Data.</td>
            </tr>
        {%endif%}
        </tbody>
    </table>
    
    {% include "board/post_pagination.html" %}
    <!-- Search input/btn -->
    <div class="row my-3">
        <div class="col-4 start-50 translate-middle-x input-group" style="width: 400px">
            <input type="text" class="search form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-light" type="button" id="btn_search">Search</button>
            </div>
        </div>
    </div>
    <!-- Search Form -->
    <form id="searchForm" method="get" action="{% url 'board:category' category.url %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="so" name="so" value="{{ so }}">
    </form>

</div>
{% endblock %}


{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $('.page-link').on('click', function(){
            $('#page').val($(this).data('page'));
            $('#searchForm').submit();
        });

        $('#btn_search').on('click', function(){
            $('#kw').val($('.kw').val());
            $('#page').val(1);
            $('#searchForm').submit();
        });

        $(".so").on('change', function() {
            $("#so").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
        $('.search').on('keydown', function(event){
            if(event.keyCode==13){
                $('#kw').val($('.kw').val());
                $('#page').val(1);
                $('#searchForm').submit();
            }
        })
    });
</script>
{% endblock %}

templates/board/reply_form.html
<!-- Reply To -->
<div class="container container-fluid border-top pt-3">
    <form id="replyForm" action="{% url 'board:comment_create' post.id %}" method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <!-- Header -->
        <label for="content" class="form-label">Reply</label>
        <!-- Input Area -->
        <div class="row justify-content-center">
            <div class="col-11">
                <textarea 
                {% if not user.is_authenticated %}disabled placeholder="Need login"{% endif %}
                placeholder="Content" class="reply form-control" name="content" 
                id="content" rows="3" style="resize: none;"></textarea>
            </div>
        </div>
        <!-- Submit Button -->
        <div class="row pt-3">
            <div class="col-11 text-end">
                <button type="submit" class="btn btn-outline-light">Submit</button>
            </div>
        </div>
    </form>
</div>